# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AccessTokenUser(UniversalBaseModel):
    """
    Information in an Access Token about the logged-in User.
    """

    id: str = pydantic.Field()
    """
    The User's ID.
    """

    email: str = pydantic.Field()
    """
    The User's email.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
