# coding: utf-8

"""
    BioT Organization Service

    APIs document (version: 9.2.19)

    The version of the OpenAPI document: 9.2.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_organization_sdk.models.built_in_template_props import BuiltInTemplateProps

class TestBuiltInTemplateProps(unittest.TestCase):
    """BuiltInTemplateProps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuiltInTemplateProps:
        """Test BuiltInTemplateProps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuiltInTemplateProps`
        """
        model = BuiltInTemplateProps()
        if include_optional:
            return BuiltInTemplateProps(
                name = '',
                id = ''
            )
        else:
            return BuiltInTemplateProps(
                name = '',
                id = '',
        )
        """

    def testBuiltInTemplateProps(self):
        """Test BuiltInTemplateProps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
