# coding: utf-8

"""
    BioT Organization Service

    APIs document (version: 9.2.19)

    The version of the OpenAPI document: 9.2.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_organization_sdk.models.search_response_organization_user_response import SearchResponseOrganizationUserResponse

class TestSearchResponseOrganizationUserResponse(unittest.TestCase):
    """SearchResponseOrganizationUserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchResponseOrganizationUserResponse:
        """Test SearchResponseOrganizationUserResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchResponseOrganizationUserResponse`
        """
        model = SearchResponseOrganizationUserResponse()
        if include_optional:
            return SearchResponseOrganizationUserResponse(
                data = [
                    biotmed_organization_sdk.models.organization_user_response.OrganizationUserResponse(
                        _name = biotmed_organization_sdk.models.name.Name(
                            first_name = 'John', 
                            last_name = 'Smith', ), 
                        _description = 'Lorem Ipsum', 
                        _email = 'john.smith@biot-med.com', 
                        _phone = '+12345678901', 
                        _locale = 'en-us', 
                        _gender = 'FEMALE', 
                        _date_of_birth = '2007-12-20', 
                        _address = biotmed_organization_sdk.models.address.Address(
                            country_code = 'US', 
                            state = 'Massachusetts', 
                            city = 'Boston', 
                            zip_code = '02101', 
                            address1 = '11', 
                            address2 = 'Entry B, Apartment 1', ), 
                        _mfa = biotmed_organization_sdk.models.mfa_dto.MfaDto(
                            enabled = True, 
                            expiration_in_minutes = 1, ), 
                        _credential_type = 'PASSWORD', 
                        _employee_id = '', 
                        _owner_organization = biotmed_organization_sdk.models.basic_referenced_entity_data_uuidid.BasicReferencedEntityDataUUIDId(
                            id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                            template_id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                            parent_entity_id = '', 
                            template_name = '', 
                            name = '', ), 
                        _id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                        _creation_time = '2007-12-20T10:15:30Z', 
                        _last_modified_time = '2007-12-20T10:15:30Z', 
                        _invitation_accepted = True, 
                        _enabled = 'ENABLED|DISABLED', 
                        _caption = '', )
                    ],
                metadata = biotmed_organization_sdk.models.metadata.Metadata(
                    sort = [
                        biotmed_organization_sdk.models.order.Order(
                            prop = '', 
                            order = 'ASC', )
                        ], 
                    filter = {
                        'key' : biotmed_organization_sdk.models.filter_v2.FilterV2(
                            in = [
                                ''
                                ], 
                            eq = null, 
                            lt = 20, 
                            lte = 25, 
                            gt = 25, 
                            gte = 25, 
                            like = 'John', 
                            from = '2007-12-20', 
                            to = '2007-12-20', 
                            is_null = True, 
                            is_not_null = True, 
                            not = null, 
                            not_in = [
                                ''
                                ], )
                        }, 
                    page = biotmed_organization_sdk.models.page_metadata.PageMetadata(
                        total_results = 145, 
                        limit = 100, ), 
                    free_text_search = 'cat dog', )
            )
        else:
            return SearchResponseOrganizationUserResponse(
                data = [
                    biotmed_organization_sdk.models.organization_user_response.OrganizationUserResponse(
                        _name = biotmed_organization_sdk.models.name.Name(
                            first_name = 'John', 
                            last_name = 'Smith', ), 
                        _description = 'Lorem Ipsum', 
                        _email = 'john.smith@biot-med.com', 
                        _phone = '+12345678901', 
                        _locale = 'en-us', 
                        _gender = 'FEMALE', 
                        _date_of_birth = '2007-12-20', 
                        _address = biotmed_organization_sdk.models.address.Address(
                            country_code = 'US', 
                            state = 'Massachusetts', 
                            city = 'Boston', 
                            zip_code = '02101', 
                            address1 = '11', 
                            address2 = 'Entry B, Apartment 1', ), 
                        _mfa = biotmed_organization_sdk.models.mfa_dto.MfaDto(
                            enabled = True, 
                            expiration_in_minutes = 1, ), 
                        _credential_type = 'PASSWORD', 
                        _employee_id = '', 
                        _owner_organization = biotmed_organization_sdk.models.basic_referenced_entity_data_uuidid.BasicReferencedEntityDataUUIDId(
                            id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                            template_id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                            parent_entity_id = '', 
                            template_name = '', 
                            name = '', ), 
                        _id = '3fa85f64-5717-4562-b3fc-2c963f66afa6', 
                        _creation_time = '2007-12-20T10:15:30Z', 
                        _last_modified_time = '2007-12-20T10:15:30Z', 
                        _invitation_accepted = True, 
                        _enabled = 'ENABLED|DISABLED', 
                        _caption = '', )
                    ],
                metadata = biotmed_organization_sdk.models.metadata.Metadata(
                    sort = [
                        biotmed_organization_sdk.models.order.Order(
                            prop = '', 
                            order = 'ASC', )
                        ], 
                    filter = {
                        'key' : biotmed_organization_sdk.models.filter_v2.FilterV2(
                            in = [
                                ''
                                ], 
                            eq = null, 
                            lt = 20, 
                            lte = 25, 
                            gt = 25, 
                            gte = 25, 
                            like = 'John', 
                            from = '2007-12-20', 
                            to = '2007-12-20', 
                            is_null = True, 
                            is_not_null = True, 
                            not = null, 
                            not_in = [
                                ''
                                ], )
                        }, 
                    page = biotmed_organization_sdk.models.page_metadata.PageMetadata(
                        total_results = 145, 
                        limit = 100, ), 
                    free_text_search = 'cat dog', ),
        )
        """

    def testSearchResponseOrganizationUserResponse(self):
        """Test SearchResponseOrganizationUserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
