# coding: utf-8

"""
    BioT Organization Service

    APIs document (version: 9.2.19)

    The version of the OpenAPI document: 9.2.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_organization_sdk.api.patient_alert_api_api import PatientAlertAPIApi


class TestPatientAlertAPIApi(unittest.TestCase):
    """PatientAlertAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PatientAlertAPIApi()

    def tearDown(self) -> None:
        pass

    def test_create_alert(self) -> None:
        """Test case for create_alert

        Create a new Patient Alert by Template id
        """
        pass

    def test_create_alert_by_template_name(self) -> None:
        """Test case for create_alert_by_template_name

        Create a new Patient Alert by Template name
        """
        pass

    def test_delete_alert(self) -> None:
        """Test case for delete_alert

        Delete Patient Alert
        """
        pass

    def test_get_alert(self) -> None:
        """Test case for get_alert

        Get Patient Alert by ID
        """
        pass

    def test_search_alerts(self) -> None:
        """Test case for search_alerts

        Search Patient Alert entities by filter
        """
        pass

    def test_search_current_alerts(self) -> None:
        """Test case for search_current_alerts

        Search open patient's alerts entities by filter
        """
        pass

    def test_update_alert(self) -> None:
        """Test case for update_alert

        Update Patient Alert
        """
        pass


if __name__ == '__main__':
    unittest.main()
