# coding: utf-8

"""
    BioT Organization Service

    APIs document (version: 9.2.19)

    The version of the OpenAPI document: 9.2.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_organization_sdk.api.internal_entity_api_api import InternalEntityAPIApi


class TestInternalEntityAPIApi(unittest.TestCase):
    """InternalEntityAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InternalEntityAPIApi()

    def tearDown(self) -> None:
        pass

    def test_has_only_built_in_data(self) -> None:
        """Test case for has_only_built_in_data

        Check if the service has only built in data.
        """
        pass

    def test_is_attribute_and_template_in_use(self) -> None:
        """Test case for is_attribute_and_template_in_use

        Check if custom/built-in attributes and template are in use.
        """
        pass


if __name__ == '__main__':
    unittest.main()
