
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-08T05:22:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b179a391f326426a8e48dccc7d71cee1990361ed",
 "version": "1.32.0.post0.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
