# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Battery.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'Battery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rBattery.proto\x12\x0fkeelson.battery\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n\x0c\x42\x61tteryState\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07voltage\x18\x02 \x01(\x01\x12\x14\n\x0c\x63urrent_amps\x18\x03 \x01(\x01\x12\x1b\n\x13temperature_celsius\x18\x04 \x01(\x01\x12\"\n\x1astate_of_charge_percentage\x18\x05 \x01(\x01\x12\x13\n\x0bis_charging\x18\x06 \x01(\x08\"\xec\x02\n\x12\x42\x61tteryInformation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x63\x61pacity_ah\x18\x02 \x01(\x02\x12\x17\n\x0fvoltage_nominal\x18\x03 \x01(\x02\x12\x13\n\x0bvoltage_min\x18\x04 \x01(\x02\x12\x13\n\x0bvoltage_max\x18\x05 \x01(\x02\x12\x18\n\x10\x63urrent_max_amps\x18\x06 \x01(\x02\x12\x45\n\x0c\x62\x61ttery_type\x18\x07 \x01(\x0e\x32/.keelson.battery.BatteryInformation.BatteryType\x12\x15\n\rserial_number\x18\x08 \x01(\t\x12\x14\n\x0cmanufacturer\x18\t \x01(\t\"A\n\x0b\x42\x61tteryType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04LIPO\x10\x01\x12\t\n\x05LIION\x10\x02\x12\x08\n\x04NIMH\x10\x03\x12\x06\n\x02PB\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Battery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTERYSTATE']._serialized_start=68
  _globals['_BATTERYSTATE']._serialized_end=254
  _globals['_BATTERYINFORMATION']._serialized_start=257
  _globals['_BATTERYINFORMATION']._serialized_end=621
  _globals['_BATTERYINFORMATION_BATTERYTYPE']._serialized_start=556
  _globals['_BATTERYINFORMATION_BATTERYTYPE']._serialized_end=621
# @@protoc_insertion_point(module_scope)
