# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WindPower.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'WindPower.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fWindPower.proto\x12\x11keelson.windpower\"\xab\x01\n\x10SailControlState\x12\x15\n\rsheeting_mode\x18\x01 \x01(\x05\x12\x1d\n\x15\x63oupled_steering_mode\x18\x02 \x01(\x05\x12\x1c\n\x14variable_thrust_mode\x18\x03 \x01(\x05\x12\x1f\n\x17variable_thrust_set_pct\x18\x04 \x01(\x02\x12\"\n\x1avariable_thrust_actual_pct\x18\x05 \x01(\x02\"\x9f\x02\n\tSailState\x12\x16\n\x0eis_active_mode\x18\x01 \x01(\x05\x12!\n\x19sheeting_angle_actual_deg\x18\x02 \x01(\x02\x12\x1d\n\x15\x62oom_angle_actual_deg\x18\t \x01(\x02\x12\x1e\n\x16sheeting_angle_set_deg\x18\x03 \x01(\x02\x12\x1e\n\x16sheeting_angle_add_deg\x18\x08 \x01(\x02\x12\x1e\n\x16wind_apparent_speed_ms\x18\x04 \x01(\x02\x12\x1f\n\x17wind_apparent_angle_deg\x18\x05 \x01(\x02\x12\x1a\n\x12wind_true_speed_ms\x18\x06 \x01(\x02\x12\x1b\n\x13wind_true_angle_deg\x18\x07 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WindPower_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAILCONTROLSTATE']._serialized_start=39
  _globals['_SAILCONTROLSTATE']._serialized_end=210
  _globals['_SAILSTATE']._serialized_start=213
  _globals['_SAILSTATE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
