"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from documenso_sdk import utils
from documenso_sdk.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, TypedDict


class DocumentDeleteDocumentRequestTypedDict(TypedDict):
    document_id: float


class DocumentDeleteDocumentRequest(BaseModel):
    document_id: Annotated[float, pydantic.Field(alias="documentId")]


class DocumentDeleteDocumentInternalServerErrorIssueTypedDict(TypedDict):
    message: str


class DocumentDeleteDocumentInternalServerErrorIssue(BaseModel):
    message: str


class DocumentDeleteDocumentInternalServerErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[DocumentDeleteDocumentInternalServerErrorIssue]] = None


class DocumentDeleteDocumentInternalServerError(Exception):
    r"""Internal server error"""

    data: DocumentDeleteDocumentInternalServerErrorData

    def __init__(self, data: DocumentDeleteDocumentInternalServerErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, DocumentDeleteDocumentInternalServerErrorData
        )


class DocumentDeleteDocumentBadRequestIssueTypedDict(TypedDict):
    message: str


class DocumentDeleteDocumentBadRequestIssue(BaseModel):
    message: str


class DocumentDeleteDocumentBadRequestErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[DocumentDeleteDocumentBadRequestIssue]] = None


class DocumentDeleteDocumentBadRequestError(Exception):
    r"""Invalid input data"""

    data: DocumentDeleteDocumentBadRequestErrorData

    def __init__(self, data: DocumentDeleteDocumentBadRequestErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, DocumentDeleteDocumentBadRequestErrorData)


class DocumentDeleteDocumentResponseTypedDict(TypedDict):
    r"""Successful response"""

    success: bool


class DocumentDeleteDocumentResponse(BaseModel):
    r"""Successful response"""

    success: bool
