"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from documenso_sdk import utils
from documenso_sdk.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TemplateCreateTemplateDirectLinkRequestTypedDict(TypedDict):
    template_id: float
    direct_recipient_id: NotRequired[float]
    r"""The of the recipient in the current template to transform into the primary recipient when the template is used."""


class TemplateCreateTemplateDirectLinkRequest(BaseModel):
    template_id: Annotated[float, pydantic.Field(alias="templateId")]

    direct_recipient_id: Annotated[
        Optional[float], pydantic.Field(alias="directRecipientId")
    ] = None
    r"""The of the recipient in the current template to transform into the primary recipient when the template is used."""


class TemplateCreateTemplateDirectLinkInternalServerErrorIssueTypedDict(TypedDict):
    message: str


class TemplateCreateTemplateDirectLinkInternalServerErrorIssue(BaseModel):
    message: str


class TemplateCreateTemplateDirectLinkInternalServerErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[TemplateCreateTemplateDirectLinkInternalServerErrorIssue]] = (
        None
    )


class TemplateCreateTemplateDirectLinkInternalServerError(Exception):
    r"""Internal server error"""

    data: TemplateCreateTemplateDirectLinkInternalServerErrorData

    def __init__(self, data: TemplateCreateTemplateDirectLinkInternalServerErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, TemplateCreateTemplateDirectLinkInternalServerErrorData
        )


class TemplateCreateTemplateDirectLinkBadRequestIssueTypedDict(TypedDict):
    message: str


class TemplateCreateTemplateDirectLinkBadRequestIssue(BaseModel):
    message: str


class TemplateCreateTemplateDirectLinkBadRequestErrorData(BaseModel):
    message: str

    code: str

    issues: Optional[List[TemplateCreateTemplateDirectLinkBadRequestIssue]] = None


class TemplateCreateTemplateDirectLinkBadRequestError(Exception):
    r"""Invalid input data"""

    data: TemplateCreateTemplateDirectLinkBadRequestErrorData

    def __init__(self, data: TemplateCreateTemplateDirectLinkBadRequestErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, TemplateCreateTemplateDirectLinkBadRequestErrorData
        )


class TemplateCreateTemplateDirectLinkResponseTypedDict(TypedDict):
    r"""Successful response"""

    id: str
    template_id: float
    token: str
    created_at: str
    enabled: bool
    direct_template_recipient_id: float


class TemplateCreateTemplateDirectLinkResponse(BaseModel):
    r"""Successful response"""

    id: str

    template_id: Annotated[float, pydantic.Field(alias="templateId")]

    token: str

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]

    enabled: bool

    direct_template_recipient_id: Annotated[
        float, pydantic.Field(alias="directTemplateRecipientId")
    ]
