
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-08T15:44:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cc1c25c45a8aef9bd88dc134662795735d783f0",
 "version": "v0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
