
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-08T18:37:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b35b58d4d55a3a44207a879b6252bfaea2c9e7b",
 "version": "0.3.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
