
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-04-05T23:02:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "af7a4e10ba2e35c4180562cf62f69ba5523c6725",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
