COLUMN_MENU_LEV = 'LEV'
COLUMN_MENU_LEV_1 = f'{COLUMN_MENU_LEV} 1'
COLUMN_MENU_LEV_2 = f'{COLUMN_MENU_LEV} 2'
COLUMN_MENU_LEV_3 = f'{COLUMN_MENU_LEV} 3'
COLUMN_MENU_LEV_4 = f'{COLUMN_MENU_LEV} 4'
COLUMN_MENU_LEV_5 = f'{COLUMN_MENU_LEV} 5'

COLUMN_MENU_LEVELS = [COLUMN_MENU_LEV_1, COLUMN_MENU_LEV_2, COLUMN_MENU_LEV_3, COLUMN_MENU_LEV_4, COLUMN_MENU_LEV_5]

COLUMN_MENU_POSSIBLE_VALUES = 'POSSIBLE VALUES'
COLUMN_MENU_DEFAULT = 'DEFAULT'
COLUMN_MENU_UNIT = 'UNIT'
COLUMN_MENU_SOFTWARE_ID = 'SOFTWARE ID'
COLUMN_MENU_CODE = 'CODE'
COLUMN_MENU_TYPE = 'TYPE'
COLUMN_MENU_GROUP = 'GROUP'
COLUMN_MENU_USER_ACCESS = 'USER ACCESS'
COLUMN_MENU_INSTALLER_ACCESS = 'INSTALLER ACCESS'
COLUMN_MENU_VIEW_CONDITION = 'VIEW CONDITION'
COLUMN_MENU_DISABLED_CONDITION = 'DISABLED CONDITION'
COLUMN_MENU_CHANGE_CONDITION = 'CHANGE CONDITION'
COLUMN_MENU_XML_DIRECTIVE = 'XML DIRECTIVE'

COLUMNS_MENU = COLUMN_MENU_LEVELS + [COLUMN_MENU_POSSIBLE_VALUES, COLUMN_MENU_DEFAULT, COLUMN_MENU_UNIT, COLUMN_MENU_SOFTWARE_ID, COLUMN_MENU_CODE, COLUMN_MENU_TYPE, COLUMN_MENU_GROUP, COLUMN_MENU_USER_ACCESS, COLUMN_MENU_INSTALLER_ACCESS, COLUMN_MENU_VIEW_CONDITION, COLUMN_MENU_DISABLED_CONDITION, COLUMN_MENU_CHANGE_CONDITION]

COLUMN_INTERNAL_LAST_LEV = 'LAST_LEV'

COLUMN_DATAPOINTER_DEVICE = 'DEVICE'
COLUMN_DATAPOINTER_CHANNEL = 'CHANNEL'
COLUMN_DATAPOINTER_CODE = 'CODE'
COLUMN_DATAPOINTER_TYPE = 'TYPE'
COLUMN_DATAPOINTER_GROUP = 'GROUP'
COLUMN_DATAPOINTER_VIEW_CONDITION = 'VIEW CONDITION'
COLUMN_DATAPOINTER_DESCRIPTION = 'DESCRIPTION'
COLUMN_DATAPOINTER_UNIT = 'UNIT'
COLUMN_DATAPOINTER_USER_ACCESS = 'USER ACCESS'
COLUMN_DATAPOINTER_XML_DIRECTIVE = 'XML DIRECTIVE'

COLUMNS_DATAPOINTER = [COLUMN_DATAPOINTER_DEVICE, COLUMN_DATAPOINTER_CHANNEL, COLUMN_DATAPOINTER_CODE, COLUMN_DATAPOINTER_TYPE, COLUMN_DATAPOINTER_GROUP, COLUMN_DATAPOINTER_VIEW_CONDITION, COLUMN_DATAPOINTER_DESCRIPTION, COLUMN_DATAPOINTER_UNIT, COLUMN_DATAPOINTER_USER_ACCESS, COLUMN_DATAPOINTER_XML_DIRECTIVE]

COLUMN_ALARM_DEVICE = 'DEVICE'
COLUMN_ALARM_CHANNEL = 'CHANNEL'
COLUMN_ALARM_CODE = 'CODE'
COLUMN_ALARM_TYPE = 'TYPE'
COLUMN_ALARM_GROUP = 'GROUP'
COLUMN_ALARM_DESCRIPTION = 'DESCRIPTION'
COLUMN_ALARM_HELP = 'HELP MESSAGE'
COLUMN_ALARM_RESET = 'RESET'
COLUMN_ALARM_XML_DIRECTIVE = 'XML DIRECTIVE'

COLUMNS_ALARM = [COLUMN_ALARM_DEVICE, COLUMN_ALARM_CHANNEL, COLUMN_ALARM_CODE, COLUMN_ALARM_TYPE, COLUMN_ALARM_GROUP, COLUMN_ALARM_DESCRIPTION, COLUMN_ALARM_HELP, COLUMN_ALARM_RESET, COLUMN_ALARM_XML_DIRECTIVE]

PERMISSIONS_MAP = {
    'nv': 'none',
    'v': 'view',
    'c': 'change',
    'hide': 'none',
    'hidden': 'none',
    'read': 'view',
    'readable': 'view',
    'write': 'change',
    'writeable': 'change'
}


INVERTER_ALARM_CODES = ('ABB', 'CSVH', 'SMN')