from datetime import timedelta
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ResponseInterface(Protocol):
    @property
    def status_code(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def cookies(self) -> dict[str, str]: ...
    def json(self) -> dict[str, Any]: ...
    @property
    def encoding(self) -> str: ...
    @property
    def elapsed(self) -> timedelta: ...
    @property
    def history(self) -> list["ResponseInterface"]: ...
    @property
    def reason(self) -> str: ...
