# coding: utf-8

"""
    BioT User Management Service

    APIs document (version: 7.17.2)

    The version of the OpenAPI document: 7.17.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_ums_sdk.api.self_user_api_api import SelfUserAPIApi


class TestSelfUserAPIApi(unittest.TestCase):
    """SelfUserAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SelfUserAPIApi()

    def tearDown(self) -> None:
        pass

    def test_forgot_password(self) -> None:
        """Test case for forgot_password

        Send reset password message
        """
        pass

    def test_self_delete_user(self) -> None:
        """Test case for self_delete_user

        Self delete user
        """
        pass

    def test_self_get_user(self) -> None:
        """Test case for self_get_user

        Self get user
        """
        pass

    def test_self_register_user(self) -> None:
        """Test case for self_register_user

        Self registration of User
        """
        pass

    def test_self_update_user(self) -> None:
        """Test case for self_update_user

        Self update user
        """
        pass


if __name__ == '__main__':
    unittest.main()
