# coding: utf-8

"""
    BioT User Management Service

    APIs document (version: 7.17.2)

    The version of the OpenAPI document: 7.17.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biotmed_ums_sdk.api.group_api_api import GroupAPIApi


class TestGroupAPIApi(unittest.TestCase):
    """GroupAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupAPIApi()

    def tearDown(self) -> None:
        pass

    def test_associate_roles_to_group(self) -> None:
        """Test case for associate_roles_to_group

        Associate Roles to Group
        """
        pass

    def test_create_group(self) -> None:
        """Test case for create_group

        Create a new Group
        """
        pass

    def test_delete_group(self) -> None:
        """Test case for delete_group

        Delete Group
        """
        pass

    def test_dissociate_roles_from_group(self) -> None:
        """Test case for dissociate_roles_from_group

        Dissociate Roles from Group
        """
        pass

    def test_search_groups(self) -> None:
        """Test case for search_groups

        Search Group entities by filter
        """
        pass

    def test_update_group(self) -> None:
        """Test case for update_group

        Update Group
        """
        pass


if __name__ == '__main__':
    unittest.main()
