# coding: utf-8

"""
    Computebench Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.api.accounts_api import AccountsApi


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsApi()

    def tearDown(self) -> None:
        pass

    def test_accounts_controller_create_account(self) -> None:
        """Test case for accounts_controller_create_account

        """
        pass

    def test_accounts_controller_create_signup_code(self) -> None:
        """Test case for accounts_controller_create_signup_code

        """
        pass

    def test_accounts_controller_get_signup_code(self) -> None:
        """Test case for accounts_controller_get_signup_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
