# coding: utf-8

"""
    Computebench Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.list_workflow_task_controller_list_workflow_tasks200_response import ListWorkflowTaskControllerListWorkflowTasks200Response

class TestListWorkflowTaskControllerListWorkflowTasks200Response(unittest.TestCase):
    """ListWorkflowTaskControllerListWorkflowTasks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkflowTaskControllerListWorkflowTasks200Response:
        """Test ListWorkflowTaskControllerListWorkflowTasks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkflowTaskControllerListWorkflowTasks200Response`
        """
        model = ListWorkflowTaskControllerListWorkflowTasks200Response()
        if include_optional:
            return ListWorkflowTaskControllerListWorkflowTasks200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = do_sdk_platform.models.list_workflow_task_controller_list_workflow_tasks_200_response_data.ListWorkflowTaskController_listWorkflowTasks_200_response_data(
                    id = '', 
                    type = '', 
                    attributes = do_sdk_platform.models.workflow_task_response_dto.WorkflowTaskResponseDto(
                        name = 'Task 1', 
                        status = 'SUBMITTED', 
                        start_time = '2024-06-19T12:57:42.231Z', 
                        end_time = '2024-06-19T12:57:42.231Z', 
                        stdout = 'stdout', 
                        stderr = 'stderr', 
                        exit_code = 0, ), )
            )
        else:
            return ListWorkflowTaskControllerListWorkflowTasks200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = do_sdk_platform.models.list_workflow_task_controller_list_workflow_tasks_200_response_data.ListWorkflowTaskController_listWorkflowTasks_200_response_data(
                    id = '', 
                    type = '', 
                    attributes = do_sdk_platform.models.workflow_task_response_dto.WorkflowTaskResponseDto(
                        name = 'Task 1', 
                        status = 'SUBMITTED', 
                        start_time = '2024-06-19T12:57:42.231Z', 
                        end_time = '2024-06-19T12:57:42.231Z', 
                        stdout = 'stdout', 
                        stderr = 'stderr', 
                        exit_code = 0, ), ),
        )
        """

    def testListWorkflowTaskControllerListWorkflowTasks200Response(self):
        """Test ListWorkflowTaskControllerListWorkflowTasks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
