__title__ = "tistory-indexer"
__description__ = "Submit and check indexing status of Tistory blog posts via Google's Indexing API"
__version__ = "0.1.0"
__author__ = "OuOHoon"
__author_email__ = "begreat@kakao.com"
__license__ = "MIT"
__url__ = "https://github.com/ouohoon/tistory-indexer"
