# Generated by Django 5.1.6 on 2025-02-20 20:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enap_designsystem", "0011_enapfooter"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnapFooterSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Título do snippet", max_length=255),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("enap_footergrid", 9)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("", "Default")],
                                    "label": "Template",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Custom CSS Class",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Custom ID",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("custom_template", 0),
                                        ("custom_css_class", 1),
                                        ("custom_id", 2),
                                    ]
                                ],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Titulo",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Nome amigável",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Link", "max_length": 255, "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("settings", 3), ("title", 5), ("link", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.ListBlock",
                                (7,),
                                {"label": "Links do Footer"},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("settings", 3), ("title", 4), ("links", 8)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Enap Footer",
            },
        ),
        migrations.DeleteModel(
            name="EnapFooter",
        ),
        migrations.AddField(
            model_name="enaplayout",
            name="footer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enap_designsystem.enapfootersnippet",
            ),
        ),
    ]
