# coding: utf-8

"""
    WakaTime API

    REST API for accessing your WakaTime coding activity stats. - Uses GET for retrieval, POST/PUT/PATCH for modification. - All requests must use HTTPS. - Responses are JSON objects. Data is in the `data` key, errors in `error` or `errors`. - Refer to WakaTime usage guidelines when using the trademark or logo.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wakatime_api
from wakatime_api.api.commits_api import CommitsApi  # noqa: E501
from wakatime_api.rest import ApiException


class TestCommitsApi(unittest.TestCase):
    """CommitsApi unit test stubs"""

    def setUp(self):
        self.api = CommitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_commit(self):
        """Test case for get_commit

        Get Single Commit  # noqa: E501
        """
        pass

    def test_get_current_user_commit(self):
        """Test case for get_current_user_commit

        Get Current User's Single Commit  # noqa: E501
        """
        pass

    def test_list_commits(self):
        """Test case for list_commits

        List Project Commits  # noqa: E501
        """
        pass

    def test_list_current_user_commits(self):
        """Test case for list_current_user_commits

        List Current User's Project Commits  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
