from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ETFQuoteSnapshot(_message.Message):
    __slots__ = ["ask_iopv", "bid_iopv", "constituent_nums", "currency_id", "down_limit_nums", "etf_ask_premium_rate", "etf_ask_price", "etf_bid_premium_rate", "etf_bid_price", "etf_deviation", "etf_last_price", "etf_pct_change", "etf_pre_close_price", "etf_premium_rate", "index_deviation", "index_last_price", "index_pct_change", "index_pre_close_price", "instrument_id", "iopv", "iopv_pct_change", "last_timestamp", "market", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "pre_close_iopv", "security_id", "security_type", "signal_id", "suspension_nums", "symbol", "up_limit_nums"]
    ASK_IOPV_FIELD_NUMBER: _ClassVar[int]
    BID_IOPV_FIELD_NUMBER: _ClassVar[int]
    CONSTITUENT_NUMS_FIELD_NUMBER: _ClassVar[int]
    CURRENCY_ID_FIELD_NUMBER: _ClassVar[int]
    DOWN_LIMIT_NUMS_FIELD_NUMBER: _ClassVar[int]
    ETF_ASK_PREMIUM_RATE_FIELD_NUMBER: _ClassVar[int]
    ETF_ASK_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_BID_PREMIUM_RATE_FIELD_NUMBER: _ClassVar[int]
    ETF_BID_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_DEVIATION_FIELD_NUMBER: _ClassVar[int]
    ETF_LAST_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_PCT_CHANGE_FIELD_NUMBER: _ClassVar[int]
    ETF_PREMIUM_RATE_FIELD_NUMBER: _ClassVar[int]
    ETF_PRE_CLOSE_PRICE_FIELD_NUMBER: _ClassVar[int]
    INDEX_DEVIATION_FIELD_NUMBER: _ClassVar[int]
    INDEX_LAST_PRICE_FIELD_NUMBER: _ClassVar[int]
    INDEX_PCT_CHANGE_FIELD_NUMBER: _ClassVar[int]
    INDEX_PRE_CLOSE_PRICE_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    IOPV_FIELD_NUMBER: _ClassVar[int]
    IOPV_PCT_CHANGE_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    PRE_CLOSE_IOPV_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_ID_FIELD_NUMBER: _ClassVar[int]
    SUSPENSION_NUMS_FIELD_NUMBER: _ClassVar[int]
    SYMBOL_FIELD_NUMBER: _ClassVar[int]
    UP_LIMIT_NUMS_FIELD_NUMBER: _ClassVar[int]
    ask_iopv: int
    bid_iopv: int
    constituent_nums: int
    currency_id: str
    down_limit_nums: int
    etf_ask_premium_rate: float
    etf_ask_price: int
    etf_bid_premium_rate: float
    etf_bid_price: int
    etf_deviation: float
    etf_last_price: int
    etf_pct_change: float
    etf_pre_close_price: int
    etf_premium_rate: float
    index_deviation: float
    index_last_price: int
    index_pct_change: float
    index_pre_close_price: int
    instrument_id: str
    iopv: int
    iopv_pct_change: float
    last_timestamp: int
    market: str
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    pre_close_iopv: int
    security_id: str
    security_type: str
    signal_id: int
    suspension_nums: int
    symbol: str
    up_limit_nums: int
    def __init__(self, msg_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., instrument_id: _Optional[str] = ..., security_id: _Optional[str] = ..., market: _Optional[str] = ..., currency_id: _Optional[str] = ..., security_type: _Optional[str] = ..., symbol: _Optional[str] = ..., constituent_nums: _Optional[int] = ..., suspension_nums: _Optional[int] = ..., up_limit_nums: _Optional[int] = ..., down_limit_nums: _Optional[int] = ..., bid_iopv: _Optional[int] = ..., ask_iopv: _Optional[int] = ..., iopv: _Optional[int] = ..., pre_close_iopv: _Optional[int] = ..., iopv_pct_change: _Optional[float] = ..., etf_last_price: _Optional[int] = ..., etf_bid_price: _Optional[int] = ..., etf_ask_price: _Optional[int] = ..., etf_pre_close_price: _Optional[int] = ..., etf_pct_change: _Optional[float] = ..., index_last_price: _Optional[int] = ..., index_pre_close_price: _Optional[int] = ..., index_pct_change: _Optional[float] = ..., index_deviation: _Optional[float] = ..., etf_deviation: _Optional[float] = ..., etf_bid_premium_rate: _Optional[float] = ..., etf_ask_premium_rate: _Optional[float] = ..., etf_premium_rate: _Optional[float] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., signal_id: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ...) -> None: ...

class ETFQuoteTick(_message.Message):
    __slots__ = ["ask_iopv", "bid_iopv", "constituent_nums", "down_limit_nums", "etf_ask_price", "etf_bid_price", "etf_last_price", "etf_pct_change", "etf_pre_close_price", "etf_premium_rate", "instrument_id", "iopv", "last_timestamp", "market", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "security_id", "security_type", "signal_id", "suspension_nums", "symbol", "up_limit_nums"]
    ASK_IOPV_FIELD_NUMBER: _ClassVar[int]
    BID_IOPV_FIELD_NUMBER: _ClassVar[int]
    CONSTITUENT_NUMS_FIELD_NUMBER: _ClassVar[int]
    DOWN_LIMIT_NUMS_FIELD_NUMBER: _ClassVar[int]
    ETF_ASK_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_BID_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_LAST_PRICE_FIELD_NUMBER: _ClassVar[int]
    ETF_PCT_CHANGE_FIELD_NUMBER: _ClassVar[int]
    ETF_PREMIUM_RATE_FIELD_NUMBER: _ClassVar[int]
    ETF_PRE_CLOSE_PRICE_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    IOPV_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_ID_FIELD_NUMBER: _ClassVar[int]
    SUSPENSION_NUMS_FIELD_NUMBER: _ClassVar[int]
    SYMBOL_FIELD_NUMBER: _ClassVar[int]
    UP_LIMIT_NUMS_FIELD_NUMBER: _ClassVar[int]
    ask_iopv: int
    bid_iopv: int
    constituent_nums: int
    down_limit_nums: int
    etf_ask_price: int
    etf_bid_price: int
    etf_last_price: int
    etf_pct_change: float
    etf_pre_close_price: int
    etf_premium_rate: float
    instrument_id: str
    iopv: int
    last_timestamp: int
    market: str
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    security_id: str
    security_type: str
    signal_id: int
    suspension_nums: int
    symbol: str
    up_limit_nums: int
    def __init__(self, msg_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., instrument_id: _Optional[str] = ..., security_id: _Optional[str] = ..., market: _Optional[str] = ..., security_type: _Optional[str] = ..., symbol: _Optional[str] = ..., constituent_nums: _Optional[int] = ..., suspension_nums: _Optional[int] = ..., up_limit_nums: _Optional[int] = ..., down_limit_nums: _Optional[int] = ..., iopv: _Optional[int] = ..., etf_premium_rate: _Optional[float] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., etf_last_price: _Optional[int] = ..., etf_bid_price: _Optional[int] = ..., etf_ask_price: _Optional[int] = ..., etf_pre_close_price: _Optional[int] = ..., etf_pct_change: _Optional[float] = ..., signal_id: _Optional[int] = ..., bid_iopv: _Optional[int] = ..., ask_iopv: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ...) -> None: ...

class FXSnapshot(_message.Message):
    __slots__ = ["currency_id", "fx_market", "fx_rate", "last_timestamp", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "opposite_currency_id"]
    CURRENCY_ID_FIELD_NUMBER: _ClassVar[int]
    FX_MARKET_FIELD_NUMBER: _ClassVar[int]
    FX_RATE_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    OPPOSITE_CURRENCY_ID_FIELD_NUMBER: _ClassVar[int]
    currency_id: str
    fx_market: str
    fx_rate: float
    last_timestamp: int
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    opposite_currency_id: str
    def __init__(self, msg_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., currency_id: _Optional[str] = ..., opposite_currency_id: _Optional[str] = ..., fx_market: _Optional[str] = ..., fx_rate: _Optional[float] = ...) -> None: ...

class MDOrder(_message.Message):
    __slots__ = ["biz_index", "bs_flag", "channel_id", "instrument_id", "last_timestamp", "market", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "order_id", "order_price", "order_qty", "order_type", "security_id", "security_type", "status"]
    BIZ_INDEX_FIELD_NUMBER: _ClassVar[int]
    BS_FLAG_FIELD_NUMBER: _ClassVar[int]
    CHANNEL_ID_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    ORDER_ID_FIELD_NUMBER: _ClassVar[int]
    ORDER_PRICE_FIELD_NUMBER: _ClassVar[int]
    ORDER_QTY_FIELD_NUMBER: _ClassVar[int]
    ORDER_TYPE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    STATUS_FIELD_NUMBER: _ClassVar[int]
    biz_index: int
    bs_flag: str
    channel_id: int
    instrument_id: str
    last_timestamp: int
    market: str
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    order_id: int
    order_price: int
    order_qty: int
    order_type: str
    security_id: str
    security_type: str
    status: int
    def __init__(self, msg_type: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., instrument_id: _Optional[str] = ..., market: _Optional[str] = ..., security_id: _Optional[str] = ..., security_type: _Optional[str] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., order_id: _Optional[int] = ..., bs_flag: _Optional[str] = ..., order_price: _Optional[int] = ..., order_qty: _Optional[int] = ..., order_type: _Optional[str] = ..., channel_id: _Optional[int] = ..., biz_index: _Optional[int] = ..., status: _Optional[int] = ...) -> None: ...

class MDSnapshot(_message.Message):
    __slots__ = ["close_price", "depth_quote", "down_limit", "high_price", "instrument_id", "iopv", "last_price", "last_timestamp", "low_price", "market", "md_date", "md_time", "md_type", "msg_sequence", "msg_type", "node_name", "node_type", "open_interest", "open_price", "phase_code", "pre_close_price", "security_id", "security_type", "signal_id", "signal_name", "signal_value", "status", "trade_nums", "turnover", "up_limit", "volume"]
    CLOSE_PRICE_FIELD_NUMBER: _ClassVar[int]
    DEPTH_QUOTE_FIELD_NUMBER: _ClassVar[int]
    DOWN_LIMIT_FIELD_NUMBER: _ClassVar[int]
    HIGH_PRICE_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    IOPV_FIELD_NUMBER: _ClassVar[int]
    LAST_PRICE_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    LOW_PRICE_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MD_TYPE_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    OPEN_INTEREST_FIELD_NUMBER: _ClassVar[int]
    OPEN_PRICE_FIELD_NUMBER: _ClassVar[int]
    PHASE_CODE_FIELD_NUMBER: _ClassVar[int]
    PRE_CLOSE_PRICE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_ID_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_NAME_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_VALUE_FIELD_NUMBER: _ClassVar[int]
    STATUS_FIELD_NUMBER: _ClassVar[int]
    TRADE_NUMS_FIELD_NUMBER: _ClassVar[int]
    TURNOVER_FIELD_NUMBER: _ClassVar[int]
    UP_LIMIT_FIELD_NUMBER: _ClassVar[int]
    VOLUME_FIELD_NUMBER: _ClassVar[int]
    close_price: int
    depth_quote: _containers.RepeatedCompositeFieldContainer[QuoteLevelData]
    down_limit: int
    high_price: int
    instrument_id: str
    iopv: int
    last_price: int
    last_timestamp: int
    low_price: int
    market: str
    md_date: int
    md_time: int
    md_type: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    open_interest: int
    open_price: int
    phase_code: int
    pre_close_price: int
    security_id: str
    security_type: str
    signal_id: int
    signal_name: str
    signal_value: int
    status: int
    trade_nums: int
    turnover: int
    up_limit: int
    volume: int
    def __init__(self, msg_type: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., instrument_id: _Optional[str] = ..., market: _Optional[str] = ..., security_id: _Optional[str] = ..., security_type: _Optional[str] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., md_type: _Optional[int] = ..., last_price: _Optional[int] = ..., volume: _Optional[int] = ..., turnover: _Optional[int] = ..., high_price: _Optional[int] = ..., low_price: _Optional[int] = ..., open_price: _Optional[int] = ..., close_price: _Optional[int] = ..., pre_close_price: _Optional[int] = ..., up_limit: _Optional[int] = ..., down_limit: _Optional[int] = ..., iopv: _Optional[int] = ..., open_interest: _Optional[int] = ..., trade_nums: _Optional[int] = ..., status: _Optional[int] = ..., phase_code: _Optional[int] = ..., signal_value: _Optional[int] = ..., signal_id: _Optional[int] = ..., signal_name: _Optional[str] = ..., depth_quote: _Optional[_Iterable[_Union[QuoteLevelData, _Mapping]]] = ...) -> None: ...

class MDTransaction(_message.Message):
    __slots__ = ["ask_order_id", "bid_order_id", "biz_index", "bs_flag", "channel_id", "instrument_id", "last_timestamp", "market", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "security_id", "security_type", "status", "trade_index", "trade_price", "trade_qty", "trade_type"]
    ASK_ORDER_ID_FIELD_NUMBER: _ClassVar[int]
    BID_ORDER_ID_FIELD_NUMBER: _ClassVar[int]
    BIZ_INDEX_FIELD_NUMBER: _ClassVar[int]
    BS_FLAG_FIELD_NUMBER: _ClassVar[int]
    CHANNEL_ID_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    STATUS_FIELD_NUMBER: _ClassVar[int]
    TRADE_INDEX_FIELD_NUMBER: _ClassVar[int]
    TRADE_PRICE_FIELD_NUMBER: _ClassVar[int]
    TRADE_QTY_FIELD_NUMBER: _ClassVar[int]
    TRADE_TYPE_FIELD_NUMBER: _ClassVar[int]
    ask_order_id: int
    bid_order_id: int
    biz_index: int
    bs_flag: str
    channel_id: int
    instrument_id: str
    last_timestamp: int
    market: str
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    security_id: str
    security_type: str
    status: int
    trade_index: int
    trade_price: int
    trade_qty: int
    trade_type: str
    def __init__(self, msg_type: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., instrument_id: _Optional[str] = ..., market: _Optional[str] = ..., security_id: _Optional[str] = ..., security_type: _Optional[str] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., trade_index: _Optional[int] = ..., trade_price: _Optional[int] = ..., trade_qty: _Optional[int] = ..., bs_flag: _Optional[str] = ..., ask_order_id: _Optional[int] = ..., bid_order_id: _Optional[int] = ..., trade_type: _Optional[str] = ..., channel_id: _Optional[int] = ..., biz_index: _Optional[int] = ..., status: _Optional[int] = ...) -> None: ...

class QuoteLevelData(_message.Message):
    __slots__ = ["ask_price", "ask_volume", "bid_price", "bid_volume"]
    ASK_PRICE_FIELD_NUMBER: _ClassVar[int]
    ASK_VOLUME_FIELD_NUMBER: _ClassVar[int]
    BID_PRICE_FIELD_NUMBER: _ClassVar[int]
    BID_VOLUME_FIELD_NUMBER: _ClassVar[int]
    ask_price: int
    ask_volume: int
    bid_price: int
    bid_volume: int
    def __init__(self, bid_price: _Optional[int] = ..., bid_volume: _Optional[int] = ..., ask_price: _Optional[int] = ..., ask_volume: _Optional[int] = ...) -> None: ...

class RCParam(_message.Message):
    __slots__ = ["account_id", "buy_active_amt", "buy_active_qty", "buy_cancel_num", "buy_order_amt", "buy_order_num", "buy_order_qty", "buy_trade_amt", "buy_trade_qty", "instrument_id", "last_timestamp", "market", "msg_sequence", "msg_type", "node_name", "node_type", "security_id", "sell_active_amt", "sell_active_qty", "sell_cancel_num", "sell_order_amt", "sell_order_num", "sell_order_qty", "sell_trade_amt", "sell_trade_qty"]
    ACCOUNT_ID_FIELD_NUMBER: _ClassVar[int]
    BUY_ACTIVE_AMT_FIELD_NUMBER: _ClassVar[int]
    BUY_ACTIVE_QTY_FIELD_NUMBER: _ClassVar[int]
    BUY_CANCEL_NUM_FIELD_NUMBER: _ClassVar[int]
    BUY_ORDER_AMT_FIELD_NUMBER: _ClassVar[int]
    BUY_ORDER_NUM_FIELD_NUMBER: _ClassVar[int]
    BUY_ORDER_QTY_FIELD_NUMBER: _ClassVar[int]
    BUY_TRADE_AMT_FIELD_NUMBER: _ClassVar[int]
    BUY_TRADE_QTY_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SELL_ACTIVE_AMT_FIELD_NUMBER: _ClassVar[int]
    SELL_ACTIVE_QTY_FIELD_NUMBER: _ClassVar[int]
    SELL_CANCEL_NUM_FIELD_NUMBER: _ClassVar[int]
    SELL_ORDER_AMT_FIELD_NUMBER: _ClassVar[int]
    SELL_ORDER_NUM_FIELD_NUMBER: _ClassVar[int]
    SELL_ORDER_QTY_FIELD_NUMBER: _ClassVar[int]
    SELL_TRADE_AMT_FIELD_NUMBER: _ClassVar[int]
    SELL_TRADE_QTY_FIELD_NUMBER: _ClassVar[int]
    account_id: str
    buy_active_amt: float
    buy_active_qty: int
    buy_cancel_num: int
    buy_order_amt: float
    buy_order_num: int
    buy_order_qty: int
    buy_trade_amt: float
    buy_trade_qty: int
    instrument_id: str
    last_timestamp: int
    market: str
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    security_id: str
    sell_active_amt: float
    sell_active_qty: int
    sell_cancel_num: int
    sell_order_amt: float
    sell_order_num: int
    sell_order_qty: int
    sell_trade_amt: float
    sell_trade_qty: int
    def __init__(self, msg_type: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., account_id: _Optional[str] = ..., instrument_id: _Optional[str] = ..., market: _Optional[str] = ..., security_id: _Optional[str] = ..., buy_order_num: _Optional[int] = ..., sell_order_num: _Optional[int] = ..., buy_cancel_num: _Optional[int] = ..., sell_cancel_num: _Optional[int] = ..., buy_order_qty: _Optional[int] = ..., sell_order_qty: _Optional[int] = ..., buy_order_amt: _Optional[float] = ..., sell_order_amt: _Optional[float] = ..., buy_active_qty: _Optional[int] = ..., sell_active_qty: _Optional[int] = ..., buy_active_amt: _Optional[float] = ..., sell_active_amt: _Optional[float] = ..., buy_trade_qty: _Optional[int] = ..., sell_trade_qty: _Optional[int] = ..., buy_trade_amt: _Optional[float] = ..., sell_trade_amt: _Optional[float] = ...) -> None: ...

class SignalQuoteData(_message.Message):
    __slots__ = ["id", "value"]
    ID_FIELD_NUMBER: _ClassVar[int]
    VALUE_FIELD_NUMBER: _ClassVar[int]
    id: str
    value: int
    def __init__(self, id: _Optional[str] = ..., value: _Optional[int] = ...) -> None: ...

class SignalSnapshot(_message.Message):
    __slots__ = ["depth_quote", "instrument_id", "last_timestamp", "market", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "security_id", "security_type", "signal_id", "signal_name", "signal_quote", "signal_type", "signal_value", "symbol"]
    DEPTH_QUOTE_FIELD_NUMBER: _ClassVar[int]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MARKET_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    SECURITY_ID_FIELD_NUMBER: _ClassVar[int]
    SECURITY_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_ID_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_NAME_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_QUOTE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_VALUE_FIELD_NUMBER: _ClassVar[int]
    SYMBOL_FIELD_NUMBER: _ClassVar[int]
    depth_quote: _containers.RepeatedCompositeFieldContainer[QuoteLevelData]
    instrument_id: str
    last_timestamp: int
    market: str
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    security_id: str
    security_type: str
    signal_id: int
    signal_name: str
    signal_quote: _containers.RepeatedCompositeFieldContainer[SignalQuoteData]
    signal_type: int
    signal_value: int
    symbol: str
    def __init__(self, msg_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., instrument_id: _Optional[str] = ..., security_id: _Optional[str] = ..., market: _Optional[str] = ..., security_type: _Optional[str] = ..., symbol: _Optional[str] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., signal_type: _Optional[int] = ..., signal_id: _Optional[int] = ..., signal_name: _Optional[str] = ..., signal_value: _Optional[int] = ..., signal_quote: _Optional[_Iterable[_Union[SignalQuoteData, _Mapping]]] = ..., depth_quote: _Optional[_Iterable[_Union[QuoteLevelData, _Mapping]]] = ...) -> None: ...

class SignalTick(_message.Message):
    __slots__ = ["instrument_id", "last_timestamp", "md_date", "md_time", "msg_sequence", "msg_type", "node_name", "node_type", "signal_id", "signal_type", "signal_value"]
    INSTRUMENT_ID_FIELD_NUMBER: _ClassVar[int]
    LAST_TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    MD_DATE_FIELD_NUMBER: _ClassVar[int]
    MD_TIME_FIELD_NUMBER: _ClassVar[int]
    MSG_SEQUENCE_FIELD_NUMBER: _ClassVar[int]
    MSG_TYPE_FIELD_NUMBER: _ClassVar[int]
    NODE_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_ID_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_TYPE_FIELD_NUMBER: _ClassVar[int]
    SIGNAL_VALUE_FIELD_NUMBER: _ClassVar[int]
    instrument_id: str
    last_timestamp: int
    md_date: int
    md_time: int
    msg_sequence: int
    msg_type: int
    node_name: str
    node_type: int
    signal_id: int
    signal_type: int
    signal_value: int
    def __init__(self, msg_type: _Optional[int] = ..., msg_sequence: _Optional[int] = ..., last_timestamp: _Optional[int] = ..., node_name: _Optional[str] = ..., node_type: _Optional[int] = ..., instrument_id: _Optional[str] = ..., md_date: _Optional[int] = ..., md_time: _Optional[int] = ..., signal_type: _Optional[int] = ..., signal_id: _Optional[int] = ..., signal_value: _Optional[int] = ...) -> None: ...
