# Generated by Django 3.2.5 on 2021-07-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postergroup',
            options={'permissions': [('view_poster_of_group', 'Can view all posters of this group'), ('upload_poster_to_group', 'Can upload new posters to this group'), ('delete_poster_of_group', 'Can delete all posters of this group')], 'verbose_name': 'Poster group', 'verbose_name_plural': 'Poster groups'},
        ),
    ]
