from .qwen2 import Qwen2ForCausalLMModel
from .llama import LlamaForCausalLMModel
from .minicpm import MinicpmForCausalLMModel
from .whisper import WhisperForConditionalGeneration
from .chatglm3 import Chatglm3ForCausalLMModel
from .glm import GLMForCausalLMModel
from .gemma2 import Gemma2ForCausalLMModel
from .phi3 import Phi3ForCausalLMModel
from .phi import PhiForCausalLMModel
