SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500

STAGE_RADIUS = 170
STAGE_POSITION = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)

PLAYER_HEIGHT = 40
PLAYER_WIDTH = 40
STARTING_POSITION_MIN = 150
STARTING_POSITION_MAX = 350
PLAYER_STARTING_POSITIONS = [
    (STARTING_POSITION_MIN, STARTING_POSITION_MIN),
    (STARTING_POSITION_MAX, STARTING_POSITION_MIN),
    (STARTING_POSITION_MAX, STARTING_POSITION_MAX),
    (STARTING_POSITION_MIN, STARTING_POSITION_MAX),
]
DIRECTION_INDICATOR_SIZE = PLAYER_WIDTH / 2

DEFAULT_ROTATION = 0
PLAYER_STARTING_ROTATIONS = [315, 225, 135, 45]

BEAM_HEIGHT = 200
BEAM_WIDTH = 20
BEAM_SPEED = 4

WAVE_RADIUS_MIN = PLAYER_WIDTH
WAVE_RADIUS_MAX = PLAYER_WIDTH * 2
