# Generated by Django 3.2.13 on 2022-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icalfeedwidget',
            name='base_url',
            field=models.URLField(blank=True, help_text='The widget will have a link to visit a related website to see more events', verbose_name='Base URL of related calendar'),
        ),
        migrations.AlterField(
            model_name='rssfeedwidget',
            name='base_url',
            field=models.URLField(blank=True, help_text='The widget will have a link to visit a related website to read more news', verbose_name='Base URL of related website'),
        ),
    ]
