# generated by datamodel-codegen:
#   filename:  export/exportGeojson.json
#   timestamp: 2025-04-07T14:43:32+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class IExportGeoJSON(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exportFileName: str = Field(
        ...,
        description='The name of the exported GeoJSON file.',
        title='GeoJSON File Name',
    )
