currencies = {
    "Dollar": "$",
    "Euro": "€",
    "Yen": "¥",
    "Pound": "£",
    "Australian Dollar": "A$",
    "Canadian Dollar": "C$",
    "Franc": "CHF",
    "Yuan": "¥",
    "Krona": "kr",
    "New Zealand Dollar": "NZ$",
    "Peso": "$",
    "Singapore Dollar": "S$",
    "Hong Kong Dollar": "HK$",
    "Krone": "kr",
    "Rand": "R",
    "Rupee": "₹",
    "Real": "R$",
    "Ruble": "₽",
    "Won": "₩",
    "Lira": "₺",
    "Shekel": "₪",
    "Riyal": "﷼",
    "Rupiah": "Rp",
    "Ringgit": "RM",
    "Baht": "฿",
    "Dong": "₫",
    "Afghani": "؋",
    "Lek": "L",
    "Dram": "֏",
    "Manat": "m",
    "Taka": "৳",
    "Lev": "лв",
    "Kyat": "K",
    "Colon": "₡",
    "Kuna": "kn",
    "Kip": "₭",
    "Loti": "L",
    "Denar": "ден",
    "Ouguiya": "UM",
    "Tugrik": "₮",
    "Metical": "MT",
    "Naira": "₦",
    "Kina": "K",
    "Guarani": "₲",
    "Sol": "S/",
    "Zloty": "zł",
    "Leu": "lei",
    "Dinar": "د.ك",
    "Lilangeni": "L",
    "Somoni": "ЅM",
    "Hryvnia": "₴",
    "Shilling": "KSh",
    "Tenge": "₸",
    "Koruna": "Kč",
    "Quetzal": "Q",
    "Pula": "P",
    "Riel": "៛",
    "Cedi": "₵",
    "Lari": "ლ",
    "Forint": "Ft",
}
