"""All the exceptions specific to the `notion_annotator` project."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils/exceptions.ipynb.

# %% auto 0
__all__ = ['ValidationError', 'DuplicateError', 'NotFoundError']

# %% ../nbs/utils/exceptions.ipynb 2
class ValidationError(Exception):
    """Raised when field validation fails."""

    pass


class DuplicateError(Exception):
    """Raised when multiple items are found but only one was expected."""

    pass


class NotFoundError(Exception):
    """Raised when an item is not found."""

    pass
