# coding: utf-8

"""
    WakaTime API

    REST API for accessing your WakaTime coding activity stats. - Uses GET for retrieval, POST/PUT/PATCH for modification. - All requests must use HTTPS. - Responses are JSON objects. Data is in the `data` key, errors in `error` or `errors`. - Refer to WakaTime usage guidelines when using the trademark or logo.   # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wakatime_api
from wakatime_api.models.aggregate_stat_count import AggregateStatCount  # noqa: E501
from wakatime_api.rest import ApiException


class TestAggregateStatCount(unittest.TestCase):
    """AggregateStatCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregateStatCount(self):
        """Test AggregateStatCount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wakatime_api.models.aggregate_stat_count.AggregateStatCount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
