"""Module providing state abbreviation to census division map."""

state_to_division = {
  "CT": "New England",
  "ME": "New England",
  "MA": "New England",
  "NH": "New England",
  "RI": "New England",
  "VT": "New England",
  "NJ": "Middle Atlantic",
  "NY": "Middle Atlantic",
  "PA": "Middle Atlantic",
  "IL": "East North Central",
  "IN": "East North Central",
  "MI": "East North Central",
  "OH": "East North Central",
  "WI": "East North Central",
  "IA": "West North Central",
  "KS": "West North Central",
  "MN": "West North Central",
  "MO": "West North Central",
  "NE": "West North Central",
  "ND": "West North Central",
  "SD": "West North Central",
  "DE": "South Atlantic",
  "DC": "South Atlantic",
  "FL": "South Atlantic",
  "GA": "South Atlantic",
  "MD": "South Atlantic",
  "NC": "South Atlantic",
  "SC": "South Atlantic",
  "VA": "South Atlantic",
  "WV": "South Atlantic",
  "AL": "East South Central",
  "KY": "East South Central",
  "MS": "East South Central",
  "TN": "East South Central",
  "AR": "West South Central",
  "LA": "West South Central",
  "OK": "West South Central",
  "TX": "West South Central",
  "AZ": "Mountain",
  "CO": "Mountain",
  "ID": "Mountain",
  "MT": "Mountain",
  "NV": "Mountain",
  "NM": "Mountain",
  "UT": "Mountain",
  "WY": "Mountain",
  "AK": "Pacific",
  "CA": "Pacific",
  "HI": "Pacific",
  "OR": "Pacific",
  "WA": "Pacific",
  "PR": "Puerto Rico"
}
