# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qwak/administration/runtime_configuration/v0/logs_storage_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from _qwak_proto.qwak.administration.runtime_configuration.v0 import auth_pb2 as qwak_dot_administration_dot_runtime__configuration_dot_v0_dot_auth__pb2
from _qwak_proto.qwak.administration.runtime_configuration.v0.external import elasticsearch_config_pb2 as qwak_dot_administration_dot_runtime__configuration_dot_v0_dot_external_dot_elasticsearch__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFqwak/administration/runtime_configuration/v0/logs_storage_config.proto\x12@qwak.administration.runtime_configuration.v0.logs_storage_config\x1a\x37qwak/administration/runtime_configuration/v0/auth.proto\x1aPqwak/administration/runtime_configuration/v0/external/elasticsearch_config.proto\"\xa3\x01\n\x18LogsStorageConfiguration\x12\x7f\n\relasticsearch\x18\x01 \x01(\x0b\x32\x66.qwak.administration.runtime_configuration.v0.external.elasticsearch_config.ElasticsearchConfigurationH\x00\x42\x06\n\x04typeB=\n9com.jfrog.ml.runtime_configuration.v0.logs_storage_configP\x01\x62\x06proto3')



_LOGSSTORAGECONFIGURATION = DESCRIPTOR.message_types_by_name['LogsStorageConfiguration']
LogsStorageConfiguration = _reflection.GeneratedProtocolMessageType('LogsStorageConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _LOGSSTORAGECONFIGURATION,
  '__module__' : 'qwak.administration.runtime_configuration.v0.logs_storage_config_pb2'
  # @@protoc_insertion_point(class_scope:qwak.administration.runtime_configuration.v0.logs_storage_config.LogsStorageConfiguration)
  })
_sym_db.RegisterMessage(LogsStorageConfiguration)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n9com.jfrog.ml.runtime_configuration.v0.logs_storage_configP\001'
  _LOGSSTORAGECONFIGURATION._serialized_start=280
  _LOGSSTORAGECONFIGURATION._serialized_end=443
# @@protoc_insertion_point(module_scope)
